### ISSUE TITLE
Issue with Runner from update 4.11.0 - Data unavailable (only data about the top 10 historical runs is stored)

### ISSUE THREAD

**Issue by AJelarcic** [postmanlabs/postman-collection#378] opened 2017-06-02 14:40 UTC
Hi,

I'm running test collections using the Windows Desktop x64 version of Postman, update 4.11.0 recently installed. Here are my system properties: 

![image](https://cloud.githubusercontent.com/assets/11745941/26730622/9013d3ce-477f-11e7-8a19-52a1ca67003c.png)

Ever since downloading this recent update, my test runs will only get one response: Data unavailable (only data about the top 10 historical runs is stored). If I send a request from the "Builder", I get a normal response. Also, I can use the Collection Runner in the Chrome App without any issues.

Here's a screen shot of the response in the desktop version that is causing the issue:

![image](https://cloud.githubusercontent.com/assets/11745941/26730714/d6d9e53c-477f-11e7-8591-0416eb7e0bcc.png)

I tried deleting old test runs to clear space, but that didn't work. 

Please help! Thank you.

**Comment by pravin0** [comment] 2017-07-27 05:50
Do u get any resolution?? i am facing the same issue..... Thanks

**Comment by AJelarcic** [comment] 2017-07-27 12:05
Not yet...

**Comment by john-halbert** [comment] 2017-08-30 18:59
I'm not sure if it's the same in your situation, but I've found that I commonly encounter this error when I have a test for the specific request, and I attempt to use an undefined variable when evaluating it. 

Here's an example of what my test was doing:

```javascript
tests["Status code is 200"] = responseCode.code === 200;
var jsonData = JSON.parse(responseBody);
console.log(jsonData.success.token); // <-- here's the error. 
if (jsonData && jsonData.success && jsonData.success.token){
    postman.setEnvironmentVariable("token", jsonData.success.token);
}
```
In my case, this was only happening when I was sending a bad request, because `jsonData.success` was never defined. I solved it by taking out the console.log, and checking that values inside the expected JSON were defined:
```javascript
tests["Status code is 200"] = responseCode.code === 200;
var jsonData = JSON.parse(responseBody);
if (jsonData.success.token){
    postman.setEnvironmentVariable("token", jsonData.success.token);
}
```

Have you checked the developer tools for errors your requests may be generating? That may help isolate the issue. 

Hope this helped!

**Comment by madebysid** [comment] 2017-09-23 12:35
@AJelarcic Is your response large? This section is only for previewing the response, it does not necessarily mean that no response was received. Can you try opening the Postman Console (Ctrl+Alt+C) and restarting the run? You'll see all your requests (and responses) here, and should be able to verify if the response is correct.
Since you say the request runs fine on the Builder, can you also check if the correct environment values are being used here? We use postman-runtime to send your requests from the builder as well as the Runner, so both should behave similarly.

**Comment by pobyzaarif** [comment] 2018-02-08 12:25
i'm using csv file for throw dynamic variables in request body then try to start runner, last test (last iteration) i got Data unavailable (only data about the top 10 historical runs is stored).
its maybe something wrong in my csv data, then little bit correction **removed new line** in the end of file. so now its works perfectly. I hope this may help you.

**Comment by zill057** [comment] 2018-03-05 09:56
* After version 6.0.8 updated, the same problem showed.
* But there is one different. Everything works perfectly before I click the failed button, even get one failed result.
![image](https://user-images.githubusercontent.com/19730264/36968460-84d603b8-209d-11e8-9e5e-1fae794e7b66.png)
* But after opening the failed result tab by clicking failed button, the same issue just shows.
![image](https://user-images.githubusercontent.com/19730264/36968566-d54acad6-209d-11e8-8fe9-36f5b6f3ed24.png)
**The above 2 pictures from the same one API.**
* Then I go back the tab "All Result", everything still doesn't work, even a passed API test.
![image](https://user-images.githubusercontent.com/19730264/36968682-3ea1bf4e-209e-11e8-9bf9-06b03e32fa9b.png)

**Comment by Pawana93** [comment] 2018-03-07 08:16
Like @zill057 same problem on Ubuntu 16.04 LTS with Postman v6.0.9

**Comment by elistemann** [comment] 2018-03-29 09:16
I can confirm the issue for 6.0.9 (macOS Sierra 10.12.6). I also checked the Postman Console for errors but everything looks fine. But i noticed that it is always working for the first run. When i do retry it Postman just shows "Data unavailable..." (still no errors in the console).
It works again if i go back to "Collection Runner" tab, select my collection and environment again and do "Start run". But it's very annoying having to do this for each run and using the console is just a workaround for something that used to work in the past. The responses are relatively small (largest has been 252 B) so the response size can't be the reason.

**Comment by satuday** [comment] 2018-04-19 03:56
+1

**Comment by vdcardenas** [comment] 2018-04-25 07:40
+1
Me too for 6.0.10 (OS: Win10 1709)

**Comment by stofte** [comment] 2018-04-26 08:05
I'm not sure how to find the version number. It doesn't appear in the UI. Regardless, I've started seeing this issue after upgrading to latest release yesterday, also on Windows 10.

Size of responses are ~1000-3000 characters of json.

**Comment by nsiksnys** [comment] 2018-04-26 13:53
A temporary workaround would be to enable response logging only for failed
requests, but it depends in what you need.

2018-04-26 5:05 GMT-03:00 Svend Tofte <notifications@github.com>:

**Comment by shamasis** [comment] 2018-05-14 20:27
Closing this. Hopefully it was reported in right repository.

**Closed by shamasis** 2018-05-14 20:27 UTC
Labels: external

**Comment by Tanshixiong** [comment] 2018-05-28 14:38
also recurrence on 6.1.3, when I retry the collection

**Comment by HIkira** [comment] 2019-02-21 10:34
+1

**Comment by sniranjan** [comment] 2019-09-17 17:57
Have the same issue in Postman v7.6.0
