### ISSUE TITLE
Write new collection to file broken

### ISSUE THREAD

**Issue by dtzar** [postmanlabs/postman-collection#467] opened 2017-09-21 18:53 UTC
When you follow [your basic example](http://www.postmanlabs.com/postman-collection/Collection.html) to create a new Collection to a file on disk here:
```
var fs = require('fs'),
    Collection = require('postman-collection').Collection,
    mycollection;

myCollection = new Collection({
    info: {
        name: "my Collection"
    }
});

// log the collection to console to see its contents
fs.writeFileSync('myCollection.postman_collection', myCollection.toString());
```
The myCollection.postman_collection file is created but it only has the following present inside the file:
`[object Object]`

**Comment by shamasis** [comment] 2017-09-21 23:24
Try `myCollection.toJSON()` @dtzar

**Comment by dtzar** [comment] 2017-09-22 03:29
Did this `fs.writeFileSync('myCollection.postman_collection', myCollection.toJSON());` and same output.

**Comment by kamalaknn** [comment] 2017-09-22 07:17
@dtzar the reason you are seeing `[object Object]` as the content of the file is because you are passing an `Object` to `fs.writeFileSync`. You should convert the collection to a string before you write it out to a file.

`JSON.stringify(collection.toJSON())` would convert the collection to a JSON string. This should do the trick for you.

```js
var fs = require('fs'),
    Collection = require('postman-collection').Collection,
    mycollection;

myCollection = new Collection({
    info: {
        name: "my Collection"
    }
});

// write the collection to a file
fs.writeFileSync('myCollection.postman_collection', JSON.stringify(myCollection.toJSON()));
```

Closing this as this is not a bug with `postman-collection` itself.

**Closed by kamalaknn** 2017-09-22 07:17 UTC

**Comment by dtzar** [comment] 2017-09-22 19:49
Thanks for the response!  The updated code did resolve the problem.  That said although this isn't a bug with the SDK, this is a bug in the example documentation.  I'm starting to find more of your examples which also do not work as-is.  For instance, [this example](https://github.com/postmanlabs/postman-collection/blob/44f21b295e01661f645c19d6490984a43c9b5ea0/lib/collection/item.js#L50-L71) you have an improper string character (line 67) AND once you fix that the entire .one() is no longer a valid function.  `TypeError: myCollection.items.one(...).add is not a function`

**Comment by dtzar** [comment] 2017-09-22 19:51
@kamalaknn @shamasis Are there any working / more robust example usage/templates for the SDK you can point me to?

**Comment by kamalaknn** [comment] 2017-09-23 05:25
@dtzar The Collection SDK [documentation](http://www.postmanlabs.com/postman-collection/) should be the source of truth for any updated documentation. That said over time some of the documentation might have gone out of date. We'll do one pass over all the examples to make sure they work soon.

In the meantime, we would be glad to accept Pull Requests with fixes for the current documentation.
