### ISSUE TITLE
Getting Error when having comment in JSON raw body

### ISSUE THREAD

**Issue by sadakchap** [postmanlabs/postman-collection#1221] opened 2021-09-11 17:23 UTC
I think we have great mini-editor like feature for specifying request body. It also has ability to comment out lines as well.

### Issue Description

When sending the request with comments in raw json option, we always get error from server-side as postman never exclude these lines and server tries to parse this json body, resulting in some weird errors.

![image](https://user-images.githubusercontent.com/44117648/132955720-4ff54260-4dcb-410e-a6b7-588c4b4ca781.png)

### Suggestion

I don't know if this will be a correct solution or not, maybe 
- before sending request to server we can exclude the commented lines, so that we always send a valid json parsable object to server,
- or disable the comment feature for raw json, as [JSON does not allow comments](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json#:~:text=JSON%20does%20not%20support%20comments,configuration%20file%20format%20for%20humans.)
  
These were 2 approaches I can think of, please let me know about your thoughts.

**Comment by sadakchap** [comment] 2021-09-14 01:14
@codenirvana any thoughts? I would like to make a pr for this. @coditva @shamasis ?

**Comment by codenirvana** [comment] 2021-09-14 07:36
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3358

@sadakchap Please refer https://github.com/postmanlabs/postman-app-support/issues/3358#issuecomment-826875807 for the workaround using the `pre-request` script.

**Closed by codenirvana** 2021-09-14 07:36 UTC
